name: check
on:
  push:
    branches:
      - main

jobs:
  format_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tooling
        uses: ok-nick/setup-aftman@v0


      - name: Format Luau
        run: stylua src

      - name: Lint Luau
        run: |
          selene src
  

  # run-in-roblox isn't very reliable
  # unit-test:
  #   runs-on: windows-latest
  #   timeout-minutes: 10
  #
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #
  #     - name: Install Roblox Studio
  #       uses: OrbitalOwen/roblox-win-installer-action@1.1
  #       with:
  #         cookie: ${{ secrets.ROBLOSECURITY }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Install tooling
  #       uses: ok-nick/setup-aftman@v0
  #       with:
  #         trust-check: false
  #
  #     # TODO: have to install packages from wally
  #
  #     - name: Build place file
  #       run: rojo build bin/test.project.json --output bin/test-place.rbxlx
  #
  #     - name: Run unit tests
  #       run: run-in-roblox --place bin/test-place.rbxlx --script bin/run-ci-tests.server.lua